apiVersion: v1
data: '{{ copySecretData "stackrox" "admission-control-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: admission-control-cert.pem
  name: admission-control-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data: '{{ copySecretData "stackrox" "collector-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: collector-cert.pem
  name: collector-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data: '{{ copySecretData "stackrox" "sensor-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: sensor-cert.pem
  name: sensor-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data:
  acs-host: '{{ (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host }}:443'
kind: ConfigMap
metadata:
  name: acs-config
  namespace: rhacm-hub